# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [4]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [5]:
print(np.__version__)

2.1.3


#### 3. Create a null vector of size 10 (★☆☆)

In [6]:
null_vector = np.zeros(10)
null_vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [7]:
array = np.array([1,2,3,4,5])
memory_size = array. size * array.itemsize
print(f"memory size of the array: {memory_size}bytes")

memory size of the array: 40bytes


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [8]:
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

    Add arguments element-wise.

    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array will retain its or

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [9]:
null_vector = np.zeros(10)
null_vector[4]=1
print(null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [10]:
vector = np.arange(10, 50)
vector

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [11]:
vector = np.arange(10)
reverse_vector = vector[::-1]
reverse_vector

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [12]:
matrix = np.arange(9).reshape(3 ,3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [13]:
non_zero = np.nonzero([1,2,0,0,4,0])
non_zero 


(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [14]:
matrix = np.eye(3)
matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [15]:
array = np.random.random((3,3,3))
array

array([[[7.57468636e-02, 9.78355030e-01, 9.42756770e-01],
        [5.21740839e-01, 1.57002662e-01, 9.00121625e-01],
        [6.98383567e-01, 4.99329153e-02, 5.03992060e-01]],

       [[3.41009948e-01, 7.93431317e-01, 3.41082866e-02],
        [8.56071638e-01, 4.41379964e-01, 7.59139537e-01],
        [6.52346580e-01, 9.87475834e-02, 9.32626299e-01]],

       [[6.49870790e-01, 4.79236788e-01, 1.47548391e-01],
        [5.92748615e-01, 4.37021176e-01, 4.95761791e-04],
        [7.79776326e-02, 8.12470622e-01, 4.48440401e-01]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [16]:
array = np.random.random((10,10,10))
array_min,array_max = array.min(),array.max()
array_min,array_max

(np.float64(3.1933872826073184e-06), np.float64(0.9998458003125266))

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [17]:
random = np.random.random(30)
mean = random.mean()
mean

np.float64(0.4748286202885851)

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [18]:
array = np.ones((5,5))
array[1:-1,1:-1] = 0
print(array)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [19]:
array = np.ones((5,5))
array = np.pad(array, pad_width=1, mode="constant")
array

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [20]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
0.3 == 3 * 0.1

nan
False
False
nan
True


False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [21]:
matrix = np.diag(1+np.arange(4),k=-1)
matrix

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [22]:
matrix = np.zeros((8,8),dtype=int)
matrix[1::2,::2]=1
matrix[::2,1::2]=1
matrix

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [23]:
print(np.unravel_index(99,(6,7,8)))

(np.int64(1), np.int64(5), np.int64(3))


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [24]:
matrix = np.tile(np.array([[0,1],[1,0]]),(4,4))
matrix

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [25]:
matrix = np.random.random((5,5))
matrix = (matrix - np.mean (matrix))/(np.std(matrix))
matrix


array([[ 0.69102578, -0.85075848, -0.70852488, -1.19365837,  0.70334618],
       [ 1.29876941,  1.09840699,  0.68125448, -1.46930491, -0.63394987],
       [-0.00253837,  1.25469128, -1.57933591, -0.47456269,  0.75871171],
       [ 1.42412812, -1.73071343,  1.27422864,  0.71794458,  0.05510736],
       [-0.69252602, -1.19439692,  0.32585937,  0.95440236, -0.70760642]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [26]:
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("o", np.ubyte)])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [27]:
matrix = np.dot(np.ones((5,3)), np.ones((3,2)))
matrix
                

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [28]:
array = np.arange(11)
array[(3<array)& (array < 8)]*+ -1
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [29]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [30]:
print(Z**Z)
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
print(Z<Z>Z)

NameError: name 'Z' is not defined

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [31]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int) .astype(float))

nan
0
[-9.22337204e+18]


C:\Users\anji\AppData\Local\Temp\ipykernel_16192\1704367000.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
C:\Users\anji\AppData\Local\Temp\ipykernel_16192\1704367000.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
C:\Users\anji\AppData\Local\Temp\ipykernel_16192\1704367000.py:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int) .astype(float))


#### 29. How to round away from zero a float array ? (★☆☆)

In [32]:
z = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(z)), z))

print(np.where(z>0, np.ceil(z), np.floor(z)))


[  1.   7.  10.   1.  -4.   2.  -6.   2. -10.  -9.]
[  1.   7.  10.   1.  -4.   2.  -6.   2. -10.  -9.]


#### 30. How to find common values between two arrays? (★☆☆)

In [33]:
common = np.random.randint(0,10,10)
common2 = np.random.randint(0,10,10)
print(np.intersect1d(common,common2))

[1 6 7 8 9]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [34]:
defaults = np.seterr(all="ignore")
z = np.ones(1)/0



#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [35]:
np.sqrt(-1) == np.emath.sqrt(-1)

np.False_

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [36]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [37]:
z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
z

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [38]:
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [39]:
z = np.random.uniform(0,10,10)
 
print(z - z%1)
print(z // 1)
print(np.floor(z))
print(z.astype(int))
print(np.trunc(z))

[7. 0. 5. 1. 2. 1. 4. 1. 0. 6.]
[7. 0. 5. 1. 2. 1. 4. 1. 0. 6.]
[7. 0. 5. 1. 2. 1. 4. 1. 0. 6.]
[7 0 5 1 2 1 4 1 0 6]
[7. 0. 5. 1. 2. 1. 4. 1. 0. 6.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [40]:
matrix = np.tile(np.arange(0,5),(5,1))
print(z)

[7.81985168 0.8352035  5.90411669 1.07111259 2.21834169 1.27604623
 4.72745648 1.76185959 0.2681732  6.59412337]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [41]:
def generate():
    for x in range(10):
        yield x
z = np.fromiter(generate(),dtype=float,count=-1)
print(z)        

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [42]:
z = np.linspace(0,1,11,endpoint=False)[1:]
z

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [43]:
z = np.random.random(10)
z.sort()
z

array([0.07174114, 0.07715158, 0.12013739, 0.17282323, 0.23474991,
       0.26218676, 0.78588832, 0.90682277, 0.91674834, 0.93597386])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [44]:
array = np.arange(10)
np.add.reduce(array)

np.int64(45)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [45]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
equal = np.allclose(A,B)
print(equal)

False


#### 43. Make an array immutable (read-only) (★★☆)

In [70]:
import numpy as np

# Create an array
arr = np.array([1, 2, 3, 4, 5])

# Make the array immutable
arr.flags.writeable = False

# Try to modify the array (this will raise an error)
try:
    arr[0] = 10
except ValueError as e:
    print(e)

print(arr)

assignment destination is read-only
[1 2 3 4 5]


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [47]:
z = np.random.random((10,2))
X,Y = z[:,0], z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[1.0676977  1.1907427  1.11312332 0.78998306 0.46436905 0.76448999
 0.78867493 0.85464795 0.79965874 0.91939349]
[0.66779687 0.92103665 0.59794692 1.23818146 1.1193673  1.43415328
 1.50303712 0.6842589  0.35432467 0.79237849]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [48]:
z = np.random.random(10)
z[z.argmax()] = 0
z

array([0.96151409, 0.63544356, 0.88116572, 0.22769574, 0.01526214,
       0.        , 0.75126779, 0.91524452, 0.67794869, 0.2053125 ])

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [49]:
z = np.zeros((5,5),[('x',float),('y',float)])
z['x'],z['y'] = np.meshgrid(np.linspace(0,1,5),
                            np.linspace(0,1,5))
z

array([[(0.  , 0.  ), (0.25, 0.  ), (0.5 , 0.  ), (0.75, 0.  ),
        (1.  , 0.  )],
       [(0.  , 0.25), (0.25, 0.25), (0.5 , 0.25), (0.75, 0.25),
        (1.  , 0.25)],
       [(0.  , 0.5 ), (0.25, 0.5 ), (0.5 , 0.5 ), (0.75, 0.5 ),
        (1.  , 0.5 )],
       [(0.  , 0.75), (0.25, 0.75), (0.5 , 0.75), (0.75, 0.75),
        (1.  , 0.75)],
       [(0.  , 1.  ), (0.25, 1.  ), (0.5 , 1.  ), (0.75, 1.  ),
        (1.  , 1.  )]], dtype=[('x', '<f8'), ('y', '<f8')])

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [50]:
x = np.arange(8)
y = x + 0.5
c = 1.0 / np.subtract.outer(x,y)
print(np.linalg.det(c))

3638.163637117973


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [51]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [52]:
np.set_printoptions(threshold=float("inf"))
z = np.zeros((40,40))
z

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
   

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [53]:
z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(z-v)).argmin()
print(z[index])

15


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [58]:
z = np.zeros(10, [("position",[('x', float, 1),
                               ('y', float, 1)]),
                 ('color',    [('r', float, 1),
                               ('g', float, 1),
                               ('b', float, 1)])])

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [59]:
z = np.random.random((10,2))
x,y = np.atleast_2d(z[:,0], z[:,1])
D = np.sqrt((x-x.T)**2+ (y-y.T)**2)
D

array([[0.        , 0.31651421, 0.61716866, 0.33210248, 0.24275718,
        0.5391429 , 0.61441579, 0.26538638, 0.24624319, 0.54289021],
       [0.31651421, 0.        , 0.9197237 , 0.56356699, 0.32189492,
        0.75990809, 0.91007152, 0.30125467, 0.13510899, 0.83541634],
       [0.61716866, 0.9197237 , 0.        , 0.6498759 , 0.80054083,
        0.36388539, 0.05064033, 0.70256241, 0.86318848, 0.48688603],
       [0.33210248, 0.56356699, 0.6498759 , 0.        , 0.26367913,
        0.74777686, 0.67267632, 0.59737455, 0.43616968, 0.31083807],
       [0.24275718, 0.32189492, 0.80054083, 0.26367913, 0.        ,
        0.77824887, 0.80873514, 0.46146865, 0.18706264, 0.5671155 ],
       [0.5391429 , 0.75990809, 0.36388539, 0.74777686, 0.77824887,
        0.        , 0.31839246, 0.47400123, 0.75762418, 0.73106557],
       [0.61441579, 0.91007152, 0.05064033, 0.67267632, 0.80873514,
        0.31839246, 0.        , 0.68069123, 0.86057033, 0.52771162],
       [0.26538638, 0.30125467, 0.7025624

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [2]:
array = np.array([[1,2,3],[4,5,6],[7,8,9]])
for index, value in np.ndenumerate(array):
    print(f"index: {index}, value:{value}")

index: (0, 0), value:1
index: (0, 1), value:2
index: (0, 2), value:3
index: (1, 0), value:4
index: (1, 1), value:5
index: (1, 2), value:6
index: (2, 0), value:7
index: (2, 1), value:8
index: (2, 2), value:9


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [4]:
rows,cols = 5,5
x = np.linspace(-1, 1, cols)
y = np.linspace(-1, 1, rows)
x, y = np.meshgrid(x,y)
gaussian_array = np.exp(-(x**2 + y**2))
gaussian_array

array([[0.13533528, 0.2865048 , 0.36787944, 0.2865048 , 0.13533528],
       [0.2865048 , 0.60653066, 0.77880078, 0.60653066, 0.2865048 ],
       [0.36787944, 0.77880078, 1.        , 0.77880078, 0.36787944],
       [0.2865048 , 0.60653066, 0.77880078, 0.60653066, 0.2865048 ],
       [0.13533528, 0.2865048 , 0.36787944, 0.2865048 , 0.13533528]])

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [7]:
n = 10
p = 3
z = np.zeros((n,n))
np.put(z, np.random.choice(range(n*n), p, replace=False),1)
print(z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [8]:
x = np.random.rand(5,10)
y = x-x.mean(axis=1, keepdims=True)
y = x - x.mean(axis=1).reshape(-1, 1)
print(z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 59. How to sort an array by the nth column? (★★☆)

In [10]:
z = np.random.randint(0,10,(3,3))
print(z)
print(z[z[:,1].argsort()])

[[2 1 0]
 [9 3 1]
 [2 3 4]]
[[2 1 0]
 [9 3 1]
 [2 3 4]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [12]:
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

Z=np.array([
    [0,1,np.nan],
    [1,2,np.nan],
    [4,5,np.nan]
])
print(np.isnan(z).all(axis=0))

False
[False False False]


#### 61. Find the nearest value from a given value in an array (★★☆)

In [13]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.4785890415266979


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [14]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [15]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.name = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)


range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [16]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[2. 1. 6. 2. 2. 5. 2. 2. 5. 3.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [17]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [19]:
w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis=0)
n = len(colors)
print(n)
w, h = 256, 256
I = np.random.randint(0,4,(h,w,3), dtype=np.uint8)

I24 = np.dot(I.astype(np.uint32),[1,256,65536])

n = len(np.unique(I24))
print(n)

64
64


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [20]:
A = np.random.randint(0,10,(3,4,3,4))
sum = A.sum(axis=(-2,-1))
print(sum)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[43 58 50 55]
 [54 56 29 65]
 [37 57 66 49]]
[[43 58 50 55]
 [54 56 29 65]
 [37 57 66 49]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [21]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

[0.26084058 0.44610985 0.43953477 0.66241961 0.52665802 0.5334163
 0.6300782  0.60491478 0.5206285  0.63382107]


#### 69. How to get the diagonal of a dot product? (★★★)

In [22]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

np.diag(np.dot(A, B))
np.sum(A * B.T, axis=1)
np.einsum("ij,ji->i", A, B)

array([0.77100521, 0.6853414 , 0.86553888, 1.55228677, 0.50228551])

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [23]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [24]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])



[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★)

In [25]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [26]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 3,  4) ( 3, 25) ( 4, 25) ( 7, 12) ( 7, 54) ( 8, 18) ( 8, 29) (12, 32)
 (12, 54) (12, 88) (17, 23) (17, 62) (18, 29) (20, 71) (20, 99) (21, 67)
 (21, 68) (23, 62) (27, 40) (27, 50) (32, 88) (38, 74) (38, 95) (40, 50)
 (43, 55) (43, 73) (55, 73) (67, 68) (71, 99) (74, 95)]


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [27]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [28]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [30]:
Z = np.arange(10)
print(sliding_window_view(Z, window_shape=3))

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [31]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([-0.60424535, -0.04876279,  0.29003326, -0.24355287,  0.74563343,
       -0.13413481, -0.27516484, -0.47811581, -0.03924425,  0.12189311,
       -0.60726174, -0.30486148, -0.9254541 ,  0.49308323, -0.75422005,
       -0.0865211 , -0.13864181,  0.25370863, -0.07902325, -0.65054128,
       -0.72363355, -0.32830248,  0.08796442, -0.28980775, -0.39382429,
       -0.94387123, -0.71867677, -0.95195095, -0.42855409, -0.16138373,
        0.26680275,  0.41998398, -0.03001573,  0.52121843,  0.27444995,
        0.99120358,  0.65113105, -0.85401636, -0.72363837, -0.24509703,
       -0.93307565,  0.08989176, -0.83474932, -0.9836108 ,  0.79272535,
        0.67578129,  0.5470024 ,  0.67259345,  0.51188108,  0.07338553,
       -0.47721006, -0.2251937 ,  0.14682192, -0.44528917, -0.4358687 ,
        0.23026426,  0.08569501,  0.64303239,  0.62254601,  0.19192265,
        0.52770411,  0.92757994,  0.29993676, -0.04990579,  0.30862638,
       -0.46246963,  0.03295923, -0.72826195, -0.79975189, -0.25

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [32]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[ 4.27710269 10.41155428 13.58183812  8.09999156 11.57953469  0.7598675
  9.18332538  4.9833118   8.33074418  5.46766796]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [33]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 5.88811981  1.79191932 11.77572663  1.40615402 14.93546805  4.39445454
   3.75985348  8.80965632  1.17729769  5.84155657]
 [ 3.5690225   8.28091284  4.80684674  8.20348021  2.14393166 10.64737238
   5.86275647  4.94112434  2.27466743  4.04612021]
 [ 0.94112589  5.04389757  5.24165626  0.52482007 10.54295318 10.78593886
   8.97509517  3.0285173   4.47843681  0.99602815]
 [11.38756883 16.32393548  1.93000855 12.21295693  5.28435772 17.03553623
  10.0025678   0.19777473  7.18311753 12.02406844]
 [ 3.97519012  8.67485931  4.37499843  8.08147337  2.02217411 11.08152104
   6.27936716  4.51127384  2.70210994  4.44407239]
 [ 1.87099408  2.11404583  7.53789989  2.47854482 13.62385215  8.64673208
   7.79831598  4.62452837  2.980126    1.89897684]
 [ 4.60403681  0.52714066 10.47672998  1.52450696 14.33672409  5.68419851
   4.91380143  7.58255524  0.03444908  4.57009302]
 [ 7.12211623 11.16870137  0.8851846   0.58646044  7.2545817  16.83684011
  14.21965247  2.62763527 10.04597     7.14164849]


#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [36]:
import numpy as np

def extract_subarray(arr, center, shape, fill=0):
    
    x, y = center
    h, w = shape
    top_left_x = x - h // 2
    top_left_y = y - w // 2

    
    subarray = np.full(shape, fill)

    
    start_x = max(0, top_left_x)
    start_y = max(0, top_left_y)
    end_x = min(arr.shape[0], top_left_x + h)
    end_y = min(arr.shape[1], top_left_y + w)


    sub_start_x = max(0, -top_left_x)
    sub_start_y = max(0, -top_left_y)
    sub_end_x = sub_start_x + (end_x - start_x)
    sub_end_y = sub_start_y + (end_y - start_y)

    
    subarray[sub_start_x:sub_end_x, sub_start_y:sub_end_y] = arr[start_x:end_x, start_y:end_y]

    return subarray

arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])

center = (1, 1)
shape = (3, 3)
fill_value = 0

result = extract_subarray(arr, center, shape, fill_value)
print(result)

[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]]


#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [42]:
z = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14])
window_size = 4
R = np.lib.stride_tricks.sliding_window_view(z, window_size)
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [43]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) 
rank = np.sum(S > 1e-10)
print(rank)

10


#### 83. How to find the most frequent value in an array?

In [44]:
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

4


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [46]:
Z = np.random.randint(0,5,(10,10))
print(sliding_window_view(Z, window_shape=(3, 3)))

[[[[4 2 1]
   [3 4 3]
   [1 1 2]]

  [[2 1 0]
   [4 3 1]
   [1 2 0]]

  [[1 0 4]
   [3 1 4]
   [2 0 0]]

  [[0 4 2]
   [1 4 2]
   [0 0 1]]

  [[4 2 1]
   [4 2 4]
   [0 1 2]]

  [[2 1 4]
   [2 4 2]
   [1 2 1]]

  [[1 4 2]
   [4 2 2]
   [2 1 2]]

  [[4 2 4]
   [2 2 0]
   [1 2 1]]]


 [[[3 4 3]
   [1 1 2]
   [2 4 2]]

  [[4 3 1]
   [1 2 0]
   [4 2 2]]

  [[3 1 4]
   [2 0 0]
   [2 2 0]]

  [[1 4 2]
   [0 0 1]
   [2 0 0]]

  [[4 2 4]
   [0 1 2]
   [0 0 4]]

  [[2 4 2]
   [1 2 1]
   [0 4 1]]

  [[4 2 2]
   [2 1 2]
   [4 1 4]]

  [[2 2 0]
   [1 2 1]
   [1 4 1]]]


 [[[1 1 2]
   [2 4 2]
   [1 3 2]]

  [[1 2 0]
   [4 2 2]
   [3 2 1]]

  [[2 0 0]
   [2 2 0]
   [2 1 4]]

  [[0 0 1]
   [2 0 0]
   [1 4 3]]

  [[0 1 2]
   [0 0 4]
   [4 3 0]]

  [[1 2 1]
   [0 4 1]
   [3 0 2]]

  [[2 1 2]
   [4 1 4]
   [0 2 2]]

  [[1 2 1]
   [1 4 1]
   [2 2 2]]]


 [[[2 4 2]
   [1 3 2]
   [3 2 2]]

  [[4 2 2]
   [3 2 1]
   [2 2 2]]

  [[2 2 0]
   [2 1 4]
   [2 2 0]]

  [[2 0 0]
   [1 4 3]
   [2 0 4]]

  [[0 0 4]
   

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [47]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 6  8 13  6  9]
 [ 8  1 11 15  8]
 [13 11  0 42  4]
 [ 6 15 42  1  7]
 [ 9  8  4  7  2]]


#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [48]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [53]:
Z= np.ones((16, 16))
k = 4
print(sliding_window_view(Z, window_shape=(k, k))[::k, ::k].sum(axis=(-2, -1)))

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [54]:
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)


[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


#### 89. How to get the n largest values of an array (★★★)

In [55]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

# Slow
print (Z[np.argsort(Z)[-n:]])

# Fast
print (Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[9999 9998 9997 9996 9995]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [56]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★)

In [57]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)


[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


C:\Users\anji\AppData\Local\Temp\ipykernel_19200\3041318686.py:3: DeprecationWarning: numpy.core is deprecated and has been renamed to numpy._core. The numpy._core namespace contains private NumPy internals and its use is discouraged, as NumPy internals can change without warning in any release. In practice, most real-world usage of numpy.core is to access functionality in the public NumPy API. If that is the case, use the public NumPy API. If not, you are using NumPy internals. If you would still like to access an internal attribute, use numpy._core.records.
  R = np.core.records.fromarrays(Z.T,


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [58]:
x = np.random.rand(int(5e7))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)


885 ms ± 3.73 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
284 ms ± 18.6 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
169 ms ± 6.03 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [59]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[0 1 2 3 5 6 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [60]:
Z = np.random.randint(0,5,(10,3))
print(Z)
# solution for arrays of all dtypes (including string arrays and record arrays)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)
# soluiton for numerical arrays only, will work for any number of columns in Z
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)


[[4 4 2]
 [3 0 1]
 [0 1 3]
 [2 0 1]
 [4 1 4]
 [3 4 3]
 [0 1 3]
 [0 2 0]
 [4 0 3]
 [4 0 0]]
[[4 4 2]
 [3 0 1]
 [0 1 3]
 [2 0 1]
 [4 1 4]
 [3 4 3]
 [0 1 3]
 [0 2 0]
 [4 0 3]
 [4 0 0]]
[[4 4 2]
 [3 0 1]
 [0 1 3]
 [2 0 1]
 [4 1 4]
 [3 4 3]
 [0 1 3]
 [0 2 0]
 [4 0 3]
 [4 0 0]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [61]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])


[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [62]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)


[[0 0 0]
 [0 0 1]
 [1 1 0]
 [1 1 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [64]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       
np.einsum('i,i->i', A, B) 
np.einsum('i,i', A, B)   
np.einsum('i,j->ij', A, B)    

array([[0.27321352, 0.26051013, 0.11789472, 0.12374752, 0.18774688,
        0.32529813, 0.19077061, 0.19036728, 0.1964075 , 0.11461117],
       [0.47540453, 0.45330004, 0.20514243, 0.21532658, 0.32668851,
        0.56603423, 0.33194995, 0.33124812, 0.3417584 , 0.19942889],
       [0.26754001, 0.25510042, 0.11544654, 0.1211778 , 0.18384816,
        0.31854304, 0.1868091 , 0.18641414, 0.19232893, 0.11223117],
       [0.40441297, 0.38560931, 0.17450877, 0.18317213, 0.27790452,
        0.48150905, 0.28238028, 0.28178325, 0.29072404, 0.16964842],
       [0.6129294 , 0.58443052, 0.26448597, 0.27761618, 0.42119286,
        0.72977644, 0.42797633, 0.42707147, 0.44062215, 0.25711961],
       [0.2765721 , 0.26371255, 0.11934399, 0.12526873, 0.19005483,
        0.32929698, 0.19311573, 0.19270744, 0.19882191, 0.11602007],
       [0.46671135, 0.44501106, 0.20139123, 0.21138914, 0.32071473,
        0.55568381, 0.32587996, 0.32519097, 0.33550905, 0.19578216],
       [0.40067078, 0.38204111, 0.1728939

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [65]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)


#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [66]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])


[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [67]:
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)


[-0.09495687  0.30843554]
